/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
