<script setup lang="ts">
</script>

<template>
	<div class="flex grow flex-col items-center justify-center">
		<h2 class="mb-4 text-center text-4xl font-bold text-primary">
			Privacy Policy
		</h2>
		<p class="text-center text-xl font-medium">
			Last update: 16th of October 2023
		</p>
		<div
			class="prose prose-sm mt-8 max-w-[80ch] text-center dark:prose-invert md:prose-base prose-ol:text-neutral prose-li:marker:font-medium prose-li:marker:text-primary">
			<p>
				This Privacy Policy governs the manner in which "LivingDexTracker" collects, uses, maintains, and discloses
				personal information collected from users of the website.
			</p>
			<h3>Personal Information Collection</h3>
			<p>"LivingDexTracker" may collect the following personal information from users:</p>
			<ul>
				<li>Nickname</li>
				<li>Email</li>
				<li>Password</li>
				<li>Profile picture</li>
			</ul>
			<h3>Use of Personal Information</h3>
			<p>
				The collected personal information is used solely for the purpose of providing users with an account to save
				their generated data.
			</p>
			<h3>Third-Party Sharing</h3>
			<p>"LivingDexTracker" does not share any personal information collected from users with third parties.</p>
			<h3>Personal Information Protection</h3>
			<p>
				The personal information of users is protected by the Firebase service, ensuring the security and
				confidentiality of the data.
			</p>
			<h3>Data Retention</h3>
			<p>
				The collected personal information will be retained until the user decides to delete their account. Once the
				account is deleted, all associated personal information will be permanently removed from our servers.
			</p>
			<h3>Use of Cookies</h3>
			<p>
				"LivingDexTracker" uses local storage to cache the data generated by the logged-in user. No cookies or
				similar technologies are used on the website.
			</p>
			<h3>User Rights and Options</h3>
			<p>
				Users have the right to delete their account and any personal information stored on the "LivingDexTracker"
				servers at any time.
			</p>
			<h3>Additional Information</h3>
			<p>No additional information or specific clauses are included in this privacy policy.</p>
			<p>
				For any further inquiries or concerns regarding our privacy policy, please contact us at 
				<a href="mailto:alwe.dev@gmail.com">alwe.dev@gmail.com</a>.
			</p>
		</div>
	</div>
</template>
